options {
    directory "/var/cache/bind";
    recursion no;        // authoritative only
    allow-query { any; };
    dnssec-enable yes;
    dnssec-validation auto;
    auth-nxdomain no;    // conform to RFC1035
    listen-on { any; };
};

include "/etc/bind/named.conf.options";

zone "ryzotropik.art.br" IN {
    type master;
    file "/etc/bind/zones/ryzotropik.art.br.db";
    allow-update { none; };
};

zone "arriscada.com.br" IN {
    type master;
    file "/etc/bind/zones/arriscada.com.br.db";
    allow-update { none; };
};